apiVersion: v1

kind: ReplicationController

metadata:
  name: hello-node-rc-v11

spec:
  replicas: 2
  selector:
    app: hello-node
    awesome: app

  template:
    metadata:
      labels:
        app: hello-node
        awesome: app

    spec:
      restartPolicy: Always
      containers:
        - name: hello-node
          image: us.gcr.io/<google_project_id>/hello-node:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
